#!/bin/bash

# grab argument, minus extension (useful for compiling)
FILE=${1%%.*}

# set flags for compiling
CC="g++"
OPTFLAGS="-Og"
#CPPFLAGS="-std=c++11 -framework SFML"
CPPFLAGS="-std=c++11 -framework SFML -lsfml-graphics -lsfml-audio -lsfml-window -lsfml-system"

if [ -z "$FILE" ]
then

    ##
    # compile all
    ##

    # build all cpp to o
    for FILE in *.cpp
    do
        $CC $CPPFLAGS $OPTFLAGS -c $FILE
    done

    # compile to executable
    for FILE in *.o
    do
        $CC $CPPFLAGS $OPTFLAGS -o ${FILE%%.*} $FILE
        rm -rf $FILE
    done

elif [ "$FILE" = "clean" ]
then

    echo $0
    echo "Cleaning files"
    for FILE in ./*
    do
        if [ -x $FILE ] && [ "${FILE}" != "$0" ]
        then
            # remove executable files
            rm -rf $FILE
        fi
    done

else

    ##
    # compile the specified file
    ##

    # make sure it exists
    if ! [ -f "$FILE.cpp" ]
    then
        echo "file not found"
        exit 1
    fi

    # build
    $CC $CPPFLAGS $OPTFLAGS -c "${FILE}.cpp"

    # compile
    $CC $CPPFLAGS $OPTFLAGS -o $FILE "${FILE}.o"

    # cleanup
    rm -rf "${FILE}.o"

    # run
    ./$FILE

fi

